export const CORE = [
  {
    id: 410,
    name: "Plank",
    description:
      "Assume a push-up position, with your body in a straight line from your head to your heels. Hold this position for a desired amount of time",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Strength",
    isPower: false,
    isStrength: true,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 411,
    name: "Side Plank",
    description:
      "Lie on your side with your elbow directly under your shoulder. Push your hip off the floor and raise your body so that you are resting on your forearm and the side of your foot",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Strength",
    isPower: false,
    isStrength: true,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 412,
    name: "Hollow Hold",
    description:
      "Lie on your back with your arms stretched out above your head and your legs lifted off the ground. Tighten your abs and hold the position for time.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
];
