export const CORE = [
  {
    id: 410,
    name: "Plank",
    description:
      "Assume a push-up position, with your body in a straight line from your head to your heels. Hold this position for a desired amount of time",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 411,
    name: "Side Plank",
    description:
      "Lie on your side with your elbow directly under your shoulder. Push your hip off the floor and raise your body so that you are resting on your forearm and the side of your foot",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 412,
    name: "Hollow Hold",
    description:
      "Lie on your back with your arms stretched out above your head and your legs lifted off the ground. Tighten your abs and hold the position for time.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 413,
    name: "Plank Hold",
    description: "Get into a push-up position, with your hands shoulder-width apart and your body in a straight line from your head to your heels.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 414,
    name: "Russian Twists",
    description: "Sit on the floor with your knees bent and feet flat. Hold a weight or a medicine ball with both hands and lean back slightly. Twist your torso to the right, then to the left.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 415,
    name: "Leg Raises",
    description: "Lie on your back with your hands at your sides. Keep your legs together and raise them straight up until they are pointing to the ceiling.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 416,
    name: "Superman",
    description: "Lie facedown on a mat with your arms and legs extended. Simultaneously raise your arms, legs, and head off the mat while squeezing your lower back muscles.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 417,
    name: "Reverse Crunches",
    description: "Lie on your back with your knees bent and your hands at your sides. Bring your knees in towards your chest and lift your hips off the ground.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 418,
    name: "Hollow Hold",
    description: "Lie on your back with your arms stretched out over your head and your legs extended. Tighten your abs and lift your head, shoulders, and feet off the ground.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 419,
    name: "Scissor Kick",
    description: "Lie on your back with your hands under your lower back. Keep your legs straight and raise them 6 inches off the floor. Then, lower one leg while raising the other.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 420,
    name: "V-Ups",
    description: "Lie on your back with your arms and legs extended. Simultaneously raise your arms and legs off the ground and touch your toes.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 421,
    name: "Bicycle Crunches",
    description: "Lie on your back with your hands behind your head and your knees bent. Bring one elbow towards the opposite knee while extending the other leg. Alternate sides.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 422,
    name: "Side Plank",
    description: "Lie on your side with your elbow directly under your shoulder. Raise your hips off the ground and hold your body in a straight line.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 423,
    name: "Corkscrew",
    description: "Lie on your back with your hands behind your head and your knees bent. Keep your shoulders on the ground and rotate your hips towards one knee, then the other.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 424,
    name: "Reverse Plank",
    description: "Sit on the floor with your legs extended in front of you and your hands behind you. Raise your hips off the ground and hold your body in a straight line.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 425,
    name: "Bird Dog",
    description: "Begin on your hands and knees, with your wrists under your shoulders and your knees under your hips. Raise one arm and the opposite leg, hold for a moment then lower back to the starting position and repeat with the other arm and leg.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 426,
    name: "Plank Jacks",
    description: "Get into a plank position, with your hands shoulder-width apart and your body in a straight line from your head to your heels. Jump your feet out to the side and back together.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 427,
    name: "Seated Russian Twists",
    description: "Sit on the floor with your knees bent and feet flat. Lean back slightly, twist your torso to the right, then to the left.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 428,
    name: "Hip Thrusts",
    description: "Sit on the floor with your knees bent and feet flat. Keep your shoulders on the ground and raise your hips towards the ceiling.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 429,
    name: "Dead Bug",
    description: "Lie on your back with your arms extended towards the ceiling and your knees bent. Lower your right arm and left leg towards the floor at the same time, then return to the starting position and repeat on the other side.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 430,
    name: "Side Leg Lifts",
    description: "Lie on your side with your elbow directly under your shoulder. Raise your top leg as high as you can, then lower it back down.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: true,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 431,
    name: "Hanging Leg Raise",
    description: "Hang from a pull-up bar with your hands shoulder-width apart and raise your legs towards your chest. Lower them back down.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 432,
    name: "Plank with Shoulder Taps",
    description: "Get into a plank position, with your hands shoulder-width apart and your body in a straight line from your head to your heels. Tap one shoulder with the opposite hand, then return to the starting position and repeat on the other side.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 433,
    name: "Reverse Sit-ups",
    description: "Sit on the floor with your knees bent and your hands behind your head. Lie back and raise your legs off the ground, then sit back up.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 434,
    name: "Flutter Kicks",
    description: "Lie on your back with your hands under your lower back. Keep your legs straight and raise them 6 inches off the floor. Flutter your legs up and down.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 435,
    name: "Plank with Alternating Leg Raise",
    description: "Get into a plank position, with your hands shoulder-width apart and your body in a straight line from your head to your heels. Raise one leg off the ground and hold for a moment, then lower it back down and repeat on the other side.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 436,
    name: "Side Plank with Arm Raise",
    description: "Lie on your side with your elbow directly under your shoulder. Raise your hips off the ground and hold your body in a straight line. Raise your top arm as high as you can, then lower it back down.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
  {
    id: 437,
    name: "Seated Leg Lifts",
    description: "Sit on the floor with your legs extended in front of you and your hands behind you. Lift one leg off the ground as high as you can, then lower it back down and repeat on the other side.",
    image: null,
    usedFor: ["Core"],
    category: ["Core"],
    exerciseType: "Core",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: false,
    isCore: true,
  },
];

