/*
    {
        id: ,
        name: "",
        description: "",
        image: null,
        usedFor: [""],
        category: [""],
        exerciseType: "",
        isPower: false,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    }, 
*/

export const EXERCISES = [
    {
        id: 1,
        name: "Box Step up",
        description: "Place foot of first leg on bench. Stand on bench by extending hip and knee of first leg and place foot of second leg on bench. Step down with second leg by flexing hip and knee of first leg. Return to original standing position by placing foot of first leg to floor.",
        image: null,
        usedFor: ["Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 2,
        name: "Box jump",
        description: "Stand in front of the box with your feet shoulder-width apart. Bend into a quarter squat and swing your arms back, then swing them forward and explode up off the ground. Land on the box as softly as possible.",
        image: null,
        usedFor: ["Vertical"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 3,
        name: "Broad jump",
        description: "Stand shoulder width apart with your arms in the air. Swing arms back as you bend at the knees. Swings arms and jumps forwards, landing on the ground",
        image: null,
        usedFor: ["Precision"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 4,
        name: "Single leg box jump",
        description: "Quickly jump on and off a low platform on one leg. Be sure to land on the toes and utilize the stretch-reflex.",
        image: null,
        usedFor: ["Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 5,
        name: "Wall sit",
        description: "Place back against wall and lower down untill knees form a 90degree angle",
        image: require("./images/wallsit.jpg"),
        usedFor: ["Tendon"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: true,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 6,
        name: "Lunge",
        description: "Step forward and place foot on ground, lowering back knee to floor. Push back up to initial position",
        image: require("./images/lunge.jpg"),
        usedFor: ["Mobility", "Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 7,
        name: "Pogo jump",
        description: "Stand shoulder width apart standing on balls of feet. Quickly bounce up and down without letting your heels touch the ground",
        image: null,
        usedFor: ["Vertical", "Precision"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    },
    {
        id: 8,
        name: "Single leg wall sit",
        description: "Place back against wall and lower down untill knees form a 90degree angle. Lift one leg up and hold",
        image: null,
        usedFor: ["Tendon"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: false,
        isConditioning: true,
        isStatic: true,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 9,
        name: "Squat",
        description: "Squat down by bending hips back while allowing knees to bend forward, keeping back straight and knees pointed same direction as feet. Descend until thighs are just past parallel to floor. Squat up by extending knees and hips until legs are straight. Return and repeat.",
        image: null,
        usedFor: ["Vertical", "Precision"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 10,
        name: "Side to side bound",
        description: "Jump far to right side and land right foot with left foot off of ground. Jump far to left side landing on right foot. Continue to bound from side to side.",
        image: null,
        usedFor: ["Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    },
    {   
        id: 11,
        name: "Depth Drop",
        description: "Stand at the front edge of a box or bench. Step off to drop and land on both feet together, absorbing the force with a bend of the knees and stopping.",
        image: null,
        usedFor: ["Impact", "Vertical"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 12,
        name: "Sprint",
        description: "A run with high intensity",
        image: null,
        usedFor: ["Speed"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 13,
        name: "Single leg Hops",
        description: "Standing shoulder width apart, lift one leg up and drive through the ground with the opposite leg. Jumping upwards bend at knee to absorb and repeat.",
        image: null,
        usedFor: ["Vertical", "Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 14,
        name: "Single Leg side to side Hops",
        description: "Standing shoulder width apart, lift one leg up and drive through the ground with the opposite leg. Jumping to the side and absorbing the landing, repeat to the opposite direction.",
        image: null,
        usedFor: ["Vertical", "Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    },
    {
        id: 15,
        name: "Depth Jump",
        description: "Stand at the front edge of a box or bench. Step off to drop and land on both feet together, absorbing the force with a bend of the knees, quickly jump upwards and then land on desired surface.",
        image: null,
        usedFor: ["Vertical", "Impact"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 16,
        name: 'Cat Hang',
        description: 'Starting with hands holding on to wall and feet resting on wall. Just a simple hold',
        image: null,
        usedFor: ["Climb Up", "Cat Leap"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: false,
        isConditioning: true,
        isStatic: true,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 17,
        name: 'Front support dip',
        description: 'Starting with arms locked out bend at the elbows, lowering the chest down towards object and then pressing back up to arms locked out',
        image: null,
        usedFor: ["Climb Up"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 18,
        name: 'Incline push up',
        description: 'Keeping body straight, lower chest to edge of box or platform by bending arms. Push body up until arms are extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Dive, Kong"],
        category: ["Climb", "Vault"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 19,
        name: 'Behind the back Dip',
        description: 'Lower body by bending arms until slight stretch is felt in chest or shoulder, or rear end touches floor. Raise body and repeat.',
        image: null,
        usedFor: ["Dash", "Lazy"],
        category: ["Vault"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 20,
        name: 'Inverted row',
        description: 'Keeping body straight, pull body up to bar. Return until arms are extended and shoulders are stretched forward. Repeat.',
        image: null,
        usedFor: ["Swing"],
        category: ["Swing"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 21,
        name: 'Quadrapedal movement',
        description: 'A simple crawl performed by keeping the body low to the ground and moving one leg and the opposite hand forward at the same time.',
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    },
    {
        id: 22,
        name: 'Plyo pushup',
        description: 'Keeping body straight, lower body to floor by bending arms. Push body up rapidly so that hands lose contact with ground',
        image: null,
        usedFor: ["Kong"],
        category: ["Vault"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 23,
        name: 'Push up',
        description: 'Keeping body straight, lower body to floor by bending arms. Push body up until arms are extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Kong"],
        category: ["Climb", "Vault"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 24,
        name: 'Pull up',
        description: 'Pull body up until neck reaches height of hands. Lower body until arms and shoulders are fully extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Underbar"],
        category: ["Climb", "Swing"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 25,
        name: 'Dip',
        description: 'Lower body by bending arms, allowing elbows to flare out to sides. When slight stretch is felt in chest or shoulders, push body up until arms are straight. Repeat.',
        image: null,
        usedFor: ["Climb Up"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 26,
        name: 'Kong up',
        description: 'Pushing through arms, allow knees to come upwards and land feet on top of object. Ending in squatting or standing position. ',
        image: null,
        usedFor: ["Kong"],
        category: ["Vault"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 27,
        name: 'Bar hang',
        description: 'Holding on to a bar keep arms and body straight.',
        image: null,
        usedFor: ["Grip", "Climb Up"],
        category: ["Climb", "Swing"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 28,
        name: "Rail squat",
        description: "Standing upright on a rail, slowly lower down into a squat position and ascend back to a standing position.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    }, 
    {
        id: 29,
        name: "Rail walk",
        description: "Standing upright on a rail, position feet length wise with rail and place back foot infront of your other foot and repeat.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    }, 
    {
        id: 30,
        name: "Rail precision balance",
        description: "Standing upright with both feet perpindicular and on the balls of your feet, slightly bend knees and allow self to balance.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: false,
        isConditioning: true,
        isStatic: true,
        isWarmup: true,
        isCore: false,
    },
    {
        id: 31,
        name: "Single leg stand",
        description: "Shift the weight to one foot and lift the other leg so that the thigh is parallel to the ground.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: false,
        isConditioning: false,
        isStatic: true,
        isWarmup: true,
        isCore: false,
    },  
    {
        id: 32,
        name: "Single leg floor touch",
        description: "Standing upright lift one leg so that the thigh is parralel to the ground. Hinge at the hips untill both hands tap the ground. Raise back up and repeat.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
        isPower: false,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: true,
        isCore: false,
    }, 
    {
        id: 33,
        name: "Knees to elbows",
        description: "Hanging from a bar with straight arms, raise your hips and knees towards the bars, stopping when the knees make contact with elbows and lower back to a straight position.",
        image: null,
        usedFor: ["Core", "Lache", "Underbar"],
        category: ["Swing"],
        exerciseType: "Core",
        isPower: false,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: false,
        isCore: true,
    }, 
    {
        id: 34,
        name: "Toes to bar",
        description: "Hanging from a bar with straight arms, hinge at the hip maintaining straight legs and drive toes upwards untill contact with the bar. Lower legs back down untill body is straight",
        image: null,
        usedFor: ["Core", "Underbar"],
        category: ["Swing"],
        exerciseType: "Core",
        isPower: false,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: false,
        isCore: true,
    },
    {
        id: 35,
        name: "Climb up",
        description: "Hanging from a ledge with straight arms and feet placed on the wall. Pull from the arms while pushing off your feet, allow your chest to get over top of the wall with straight arms. Finish by getting feet on top of the wall.",
        image: null,
        usedFor: ["Climb up"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },  
    {
        id: 36,
        name: "Standing Pull Kong",
        description: "Standing upright and hands grabbing a rail or furthest edge of an obstacle. Pulling with your arms drive your knees up to clear the object, throwing it behind you and landing both feet on the ground.",
        image: null,
        usedFor: ["Kong"],
        category: ["Vault"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: false,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 37,
        name: "Cat back",
        description: "Starting with hands holding on to edge of wall and feet staggered. Drive the lower leg upwards as your arms pull into the wall. Stepping off the wall, turn your body opposite of the foot placed and land 180degrees on a flat surface.",
        image: null,
        usedFor: ["Cat Hang"],
        category: ["Climb"],
        exerciseType: "Lowerbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    },
    {
        id: 38,
        name: "Cat hang pullup with knee drive",
        description: "Starting with hands holding on to edge of wall, place one foot on the wall and one leg hanging . Drive the hanging leg upwards with your knee as your arms pull into the wall. Drive upwards rapidly to where your chin is above the ledge you are holding and then lower.",
        image: null,
        usedFor: ["Cat Hang"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,  
    },
    {
        id: 39,
        name: "Cat hang pullup",
        description: "Starting with hands holding on to edge of wall, with feet feet staggered on the wall. Without letting your feet step off the wall, pull up with your arms untill chin is above the level of surface you are holding. Lower.",
        image: null,
        usedFor: ["Cat Hang"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,  
    },
    {
        id: 40,
        name: "Superman raise",
        description: "Lie with your chest down on the floor, reaching your arms straight out in front of you. raise your arms, legs, and the top of your chest off the floor. Returning back to the starting position",
        image: null,
        usedFor: ["Lache"],
        category: ["Swing"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,  
    },
    {
        id: 41,
        name:  "Cat hang mountain climber",
        description: "Starting with hands holding on to edge of wall, with feet feet staggered on the wall. Alternate knees drives driving upwards towards chest while maintaining the hold.",
        image: null,
        usedFor: ["Cat Hang" , "Climb up", "Core"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: false,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: true,
    },
    {
        id: 42,
        name: "Dyno taps",
        description: "Start with hands holding on to edge of wall/grip hold, with feet staggered on the wall. Push off your feet simutaneously pulling upwards with both arms. Let go with one hand reaching above and tapping the wall, returning back to your starting position.",
        image: null,
        usedFor: ["Dyno"],
        category: ["Climb"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    }, 
    {
        id: 43,
        name: "Side Vault Continuous",
        description: "Placing both hands on top of thin obstacle, jump off the ground laterally while pushing through your arms to maintain hips and knees tucked in. Both feet landing on the other side of the obstacle while hands still remain in contact. Repeat.",
        image: null,
        usedFor: ["Side", "Speed"],
        category: ["Vault"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    }, 
    {
        id: 44,
        name: "Diamond push up",
        description: "Get on all fours with your hands together under your chest. Position your index fingers and thumbs so they're touching, forming a diamond shape. Extend arms to elevate, and lower to the ground, then push back up to the starting position.",
        image: null,
        usedFor: ["Climb up", "Kong Up"],
        category: ["Vault"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: true,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    }, 
    {
        id: 45,
        name: "Bar hip kip",
        description: "Hands grabbing on to bar with arms straight in a support position. Allow your legs to swing under the bar and then driving back with your heels. Pushing through you arms, allow your hands to come off the bar and land both feet ontop of the bar. Lowering back down to the initial position.",
        image: null,
        usedFor: ["Cast"],
        category: ["Swing"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    }, 
    {
        id: 46,
        name: "Hip kip",
        description: "Hands flat on top of ledge with arms in a support position. Drive upwards with the heels, leaning the chest forward. Pushing through the arms, allow your hands to come off the bar and land both feet on top of the obstacle. Lowering back down to the initial position.",
        image: null,
        usedFor: ["Cast"],
        category: ["Swing"],
        exerciseType: "Upperbody",
        isPower: true,
        isStrength: false,
        isConditioning: true,
        isStatic: false,
        isWarmup: false,
        isCore: false,
    }, 
]