/*
    {
        id: ,
        name: "",
        description: "",
        image: null,
        usedFor: [""],
        category: [""],
        exerciseType: "",
    }, 
*/

export const EXERCISES = [
    {
        id: 1,
        name: "Box Step up",
        description: "Place foot of first leg on bench. Stand on bench by extending hip and knee of first leg and place foot of second leg on bench. Step down with second leg by flexing hip and knee of first leg. Return to original standing position by placing foot of first leg to floor.",
        image: null,
        usedFor: ["Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 2,
        name: "Box jump",
        description: "Stand in front of the box with your feet shoulder-width apart. Bend into a quarter squat and swing your arms back, then swing them forward and explode up off the ground. Land on the box as softly as possible.",
        image: null,
        usedFor: ["Vertical"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 3,
        name: "Broad jump",
        description: "Stand shoulder width apart with your arms in the air. Swing arms back as you bend at the knees. Swings arms and jumps forwards, landing on the ground",
        image: null,
        usedFor: ["Precision"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 4,
        name: "1 Leg box jump",
        description: "Quickly jump on and off a low platform on one leg. Be sure to land on the toes and utilize the stretch-reflex.",
        image: null,
        usedFor: ["Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 5,
        name: "Wall sit",
        description: "Place back against wall and lower down untill knees form a 90degree angle",
        image: require("./images/wallsit.jpg"),
        usedFor: ["Tendon"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 6,
        name: "Lunge",
        description: "Step forward and place foot on ground, lowering back knee to floor. Push back up to initial position",
        image: require("./images/lunge.jpg"),
        usedFor: ["Mobility", "Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 7,
        name: "Pogo jump",
        description: "Stand shoulder width apart standing on balls of feet. Quickly bounce up and down without letting your heels touch the ground",
        image: null,
        usedFor: ["Vertical", "Precision"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 8,
        name: "Single leg wall sit",
        description: "Place back against wall and lower down untill knees form a 90degree angle. Lift one leg up and hold",
        image: null,
        usedFor: ["Tendon"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 9,
        name: "Squat",
        description: "Squat down by bending hips back while allowing knees to bend forward, keeping back straight and knees pointed same direction as feet. Descend until thighs are just past parallel to floor. Squat up by extending knees and hips until legs are straight. Return and repeat.",
        image: null,
        usedFor: ["Vertical", "Precision"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 10,
        name: "Side to side bound",
        description: "Jump far to right side and land right foot with left foot off of ground. Jump far to left side landing on right foot. Continue to bound from side to side.",
        image: null,
        usedFor: ["Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {   
        id: 11,
        name: "Depth Drop",
        description: "Stand at the front edge of a box or bench. Step off to drop and land on both feet together, absorbing the force with a bend of the knees and stopping.",
        image: null,
        usedFor: ["Impact", "Vertical"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 12,
        name: "Sprint",
        description: "A run with high intensity",
        image: null,
        usedFor: ["Speed"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 13,
        name: "Single leg Hops",
        description: "Standing shoulder width apart, lift one leg up and drive through the ground with the opposite leg. Jumping upwards bend at knee to absorb and repeat.",
        image: null,
        usedFor: ["Vertical", "Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 14,
        name: "Single Leg side to side Hops",
        description: "Standing shoulder width apart, lift one leg up and drive through the ground with the opposite leg. Jumping to the side and absorbing the landing, repeat to the opposite direction.",
        image: null,
        usedFor: ["Vertical", "Stride"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 15,
        name: "Depth Jump",
        description: "Stand at the front edge of a box or bench. Step off to drop and land on both feet together, absorbing the force with a bend of the knees, quickly jump upwards and then land on desired surface.",
        image: null,
        usedFor: ["Vertical", "Impact"],
        category: ["Jump"],
        exerciseType: "Lowerbody",
    },
    {
        id: 16,
        name: 'Cat Hang',
        description: 'Starting with hands holding on to wall and feet resting on wall. Just a simple hold',
        image: null,
        usedFor: ["Climb Up", "Cat Leap"],
        category: ["Climb"],
        exerciseType: "Upperbody",
    },
    {
        id: 17,
        name: 'Front support dip',
        description: 'Starting with arms locked out bend at the elbows, lowering the chest down towards object and then pressing back up to arms locked out',
        image: null,
        usedFor: ["Climb Up"],
        category: ["Climb"],
        exerciseType: "Upperbody",
    },
    {
        id: 18,
        name: 'Incline push up',
        description: 'Keeping body straight, lower chest to edge of box or platform by bending arms. Push body up until arms are extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Dive, Kong"],
        category: ["Climb", "Vault"],
        exerciseType: "Upperbody",
    },
    {
        id: 19,
        name: 'Behind the back Dip',
        description: 'Lower body by bending arms until slight stretch is felt in chest or shoulder, or rear end touches floor. Raise body and repeat.',
        image: null,
        usedFor: ["Dash", "Lazy"],
        category: ["Vault"],
        exerciseType: "Upperbody",
    },
    {
        id: 20,
        name: 'Inverted row',
        description: 'Keeping body straight, pull body up to bar. Return until arms are extended and shoulders are stretched forward. Repeat.',
        image: null,
        usedFor: ["Swing"],
        category: ["Swing"],
        exerciseType: "Upperbody",
    },
    {
        id: 21,
        name: 'Quadrapedal movement',
        description: 'A simple crawl performed by keeping the body low to the ground and moving one leg and the opposite hand forward at the same time.',
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Upperbody",
    },
    {
        id: 22,
        name: 'Plyo pushup',
        description: 'Keeping body straight, lower body to floor by bending arms. Push body up rapidly so that hands lose contact with ground',
        image: null,
        usedFor: ["Kong"],
        category: ["Vault"],
        exerciseType: "Upperbody",
    },
    {
        id: 23,
        name: 'Push up',
        description: 'Keeping body straight, lower body to floor by bending arms. Push body up until arms are extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Kong"],
        category: ["Climb", "Vault"],
        exerciseType: "Upperbody",
    },
    {
        id: 24,
        name: 'Pull up',
        description: 'Pull body up until neck reaches height of hands. Lower body until arms and shoulders are fully extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Underbar"],
        category: ["Climb", "Swing"],
        exerciseType: "Upperbody",
    },
    {
        id: 25,
        name: 'Dip',
        description: 'Lower body by bending arms, allowing elbows to flare out to sides. When slight stretch is felt in chest or shoulders, push body up until arms are straight. Repeat.',
        image: null,
        usedFor: ["Climb Up"],
        category: ["Climb"],
        exerciseType: "Upperbody",
    },
    {
        id: 26,
        name: 'Kong up',
        description: 'Pushing through arms, allow knees to come upwards and land feet on top of object. Ending in squatting or standing position. ',
        image: null,
        usedFor: ["Kong"],
        category: ["Vault"],
        exerciseType: "Upperbody",
    },
    {
        id: 27,
        name: 'Bar hang',
        description: 'Holding on to a bar keep arms and body straight.',
        image: null,
        usedFor: ["Grip", "Climb Up"],
        category: ["Climb", "Swing"],
        exerciseType: "Upperbody",
    },
    {
        id: 28,
        name: "Rail squat",
        description: "Standing upright on a rail, slowly lower down into a squat position and ascend back to a standing position.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
    }, 
    {
        id: 29,
        name: "Rail walk",
        description: "Standing upright on a rail, position feet length wise with rail and place back foot infront of your other foot and repeat.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
    }, 
    {
        id: 30,
        name: "Rail precision balance",
        description: "Standing upright with both feet perpindicular and on the balls of your feet, slightly bend knees and allow self to balance.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
    },
    {
        id: 31,
        name: "Single leg stand",
        description: "Shift the weight to one foot and lift the other leg so that the thigh is parallel to the ground.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
    },  
    {
        id: 32,
        name: "Single leg floor touch",
        description: "Standing upright lift one leg so that the thigh is parralel to the ground. Hinge at the hips untill both hands tap the ground. Raise back up and repeat.",
        image: null,
        usedFor: ["Balance"],
        category: ["Balance"],
        exerciseType: "Lowerbody",
    }, 
    {
        id: 33,
        name: "Knees to elbows",
        description: "Hanging from a bar with straight arms, raise your hips and knees towards the bars, stopping when the knees make contact with elbows and lower back to a straight position.",
        image: null,
        usedFor: ["Core", "Lache", "Underbar"],
        category: ["Swing"],
        exerciseType: "Core",
    }, 
    {
        id: 34,
        name: "Toes to bar",
        description: "Hanging from a bar with straight arms, hinge at the hip maintaining straight legs and drive toes upwards untill contact with the bar. Lower legs back down untill body is straight",
        image: null,
        usedFor: ["Core", "Underbar"],
        category: ["Swing"],
        exerciseType: "Core",
    }, 
]