/*
 {  
    id:,
    name: "",
    description: "",
    image: null,
    }, 
*/

export const LOWERBODY = [
    {
        id: 1,
        name: "Box Step up",
        description: "Place foot of first leg on bench. Stand on bench by extending hip and knee of first leg and place foot of second leg on bench. Step down with second leg by flexing hip and knee of first leg. Return to original standing position by placing foot of first leg to floor.",
        image: null,
        usedFor: ["Stride"],
    },
    {
        id: 2,
        name: "Box jump",
        description: "Stand in front of the box with your feet shoulder-width apart. Bend into a quarter squat and swing your arms back, then swing them forward and explode up off the ground. Land on the box as softly as possible.",
        image: null,
        usedFor: ["Vertical"],
    },
    {
        id: 3,
        name: "Broad jump",
        description: "Stand shoulder width apart with your arms in the air. Swing arms back as you bend at the knees. Swings arms and jumps forwards, landing on the ground",
        image: null,
        usedFor: ["Precision"],
    },
    {
        id: 4,
        name: "1 Leg box jump",
        description: "Quickly jump on and off a low platform on one leg. Be sure to land on the toes and utilize the stretch-reflex.",
        image: null,
        usedFor: ["Stride"],
    },
    {
        id: 5,
        name: "Wall sit",
        description: "Place back against wall and lower down untill knees form a 90degree angle",
        image: require("./images/wallsit.jpg"),
        usedFor: ["Tendon"],
    },
    {
        id: 6,
        name: "Lunge",
        description: "Step forward and place foot on ground, lowering back knee to floor. Push back up to initial position",
        image: require("./images/lunge.jpg"),
        usedFor: ["Mobility", "Stride"],
    },
    {
        id: 7,
        name: "Pogo jump",
        description: "Stand shoulder width apart standing on balls of feet. Quickly bounce up and down without letting your heels touch the ground",
        image: null,
        usedFor: ["Vertical", "Precision"],
    },
    {
        id: 8,
        name: "1 Leg wall sit",
        description: "Place back against wall and lower down untill knees form a 90degree angle. Lift one leg up and hold",
        image: null,
        usedFor: ["Tendon"],
    },
    {
        id: 9,
        name: "Squat",
        description: "Squat down by bending hips back while allowing knees to bend forward, keeping back straight and knees pointed same direction as feet. Descend until thighs are just past parallel to floor. Squat up by extending knees and hips until legs are straight. Return and repeat.",
        image: null,
        usedFor: ["Vertical", "Precision"],
    },
    {
        id: 10,
        name: "Side to side bound",
        description: "Jump far to right side and land right foot with left foot off of ground. Jump far to left side landing on right foot. Continue to bound from side to side.",
        image: null,
        usedFor: ["Stride"],
    },
    {   
        id: 11,
        name: "Depth Drop",
        description: "Stand at the front edge of a box or bench. Step off to drop and land on both feet together, absorbing the force with a bend of the knees and stopping.",
        image: null,
        usedFor: ["Impact", "Vertical"],
    },
    {
        id: 12,
        name: "Sprint",
        description: "A run with high intensity",
        image: null,
        usedFor: ["Speed"],
    },
    {
        id: 13,
        name: "Single leg Hops",
        description: "Standing shoulder width apart, lift one leg up and drive through the ground with the opposite leg. Jumping upwards bend at knee to absorb and repeat.",
        image: null,
        usedFor: ["Vertical", "Stride"],
    },
    {
        id: 14,
        name: "Single Leg side to side Hops",
        description: "Standing shoulder width apart, lift one leg up and drive through the ground with the opposite leg. Jumping to the side and absorbing the landing, repeat to the opposite direction.",
        image: null,
        usedFor: ["Vertical", "Stride"],
    },
    {
        id: 15,
        name: "Depth Jump",
        description: "Stand at the front edge of a box or bench. Step off to drop and land on both feet together, absorbing the force with a bend of the knees, quickly jump upwards and then land on desired surface.",
        image: null,
        usedFor: ["Vertical", "Precision", "Impact"],
    },
]