export const UPPERBODY = [
    {
        id: 16,
        name: 'Cat Hang',
        description: 'Starting with hands holding on to wall and feet resting on wall. Just a simple hold',
        image: null,
        usedFor: ["Climb Up"],
    },
    {
        id: 17,
        name: 'Front support dip',
        description: 'Starting with arms locked out bend at the elbows, lowering the chest down towards object and then pressing back up to arms locked out',
        image: null,
        usedFor: ["Climb Up"],
    },
    {
        id: 18,
        name: 'Incline push up',
        description: 'Keeping body straight, lower chest to edge of box or platform by bending arms. Push body up until arms are extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Vault"],
    },
    {
        id: 19,
        name: 'Behind the back Dip',
        description: 'Lower body by bending arms until slight stretch is felt in chest or shoulder, or rear end touches floor. Raise body and repeat.',
        image: null,
        usedFor: [],
    },
    {
        id: 20,
        name: 'Inverted row',
        description: 'Keeping body straight, pull body up to bar. Return until arms are extended and shoulders are stretched forward. Repeat.',
        image: null,
        usedFor: ["Swing"],
    },
    {
        id: 21,
        name: 'Quadrapedal movement',
        description: 'A simple crawl performed by keeping the body low to the ground and moving one leg and the opposite hand forward at the same time.',
        image: null,
        usedFor: ["Balance"],
    },
    {
        id: 22,
        name: 'Plyo pushup',
        description: 'Keeping body straight, lower body to floor by bending arms. Push body up rapidly so that hands lose contact with ground',
        image: null,
        usedFor: ["Vault"],
    },
    {
        id: 23,
        name: 'Push up',
        description: 'Keeping body straight, lower body to floor by bending arms. Push body up until arms are extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Vault"],
    },
    {
        id: 24,
        name: 'Pull up',
        description: 'Pull body up until neck reaches height of hands. Lower body until arms and shoulders are fully extended. Repeat.',
        image: null,
        usedFor: ["Climb Up", "Swing"],
    },
    {
        id: 25,
        name: 'Dip',
        description: 'Lower body by bending arms, allowing elbows to flare out to sides. When slight stretch is felt in chest or shoulders, push body up until arms are straight. Repeat.',
        image: null,
        usedFor: ["Climb Up"],
    },
    {
        id: 26,
        name: 'Kong up',
        description: 'Pushing through arms, allow knees to come upwards and land feet on top of object. Ending in squatting or standing position. ',
        image: null,
        usedFor: ["Vault"],
    },
    {
        id: 27,
        name: 'Bar hang',
        description: 'Holding on to the bar keeping arms and body straight',
        image: null,
        usedFor: ["Grip", "Swing"],
    }, 
]