export const WARMUPS = [{
    id: 100,
    name: "Jumping Jacks",
    description:
      "Stand with your feet together and your arms at your sides. Jump your feet out to the side and raise your arms above your head, then jump back to the starting position.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody", "Upperbody", "Full"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 101,
    name: "Walking Lunges",
    description:
      "Stand with your feet together and take a large step forward with one foot, bending both knees to 90 degrees. Keep your back straight and push back up to the starting position.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 102,
    name: "Arm Circles",
    description:
      "Stand with your feet shoulder-width apart and your arms extended straight out to your sides. Slowly make small circles with your arms, then switch directions.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Upper body"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 103,
    name: "High Knees",
    description:
      "Stand with your feet hip-width apart and your arms at your sides. Quickly bring one knee up towards your chest, then switch legs.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 104,
    name: "Butt Kicks",
    description:
      "Stand with your feet hip-width apart and your arms at your sides. Quickly kick one heel back towards your glutes, then switch legs.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 105,
    name: "Reverse Lunges",
    description:
      "Stand with your feet together and take a step backward with one foot, keeping the other foot stationary. Bend both knees to 90 degrees and then return to the starting position.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 106,
    name: "Plank Walkouts",
    description:
      "Begin in a plank position and walk your hands out as far as you can, then walk them back to the starting position.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Upperbody", "Full"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 107,
    name: "Lateral Hops",
    description:
      "Stand with your feet shoulder-width apart and hop side to side over a line or object on the ground.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
  {
    id: 108,
    name: "Inchworms",
    description:
      "Stand with your feet shoulder-width apart and bend forward to place your hands on the ground. Walk your hands out to a push-up position, then walk your feet to your hands and stand back up.",
    image: null,
    usedFor: ["Warmup"],
    category: ["Lowerbody, Upperbody", "Full"],
    exerciseType: "Warmup",
    isPower: false,
    isStrength: false,
    isConditioning: false,
    isStatic: false,
    isWarmup: true,
    isCore: false,
  },
];